server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/secure_notes
    username: postgres
    password: Enigma
  security:
    user:
      name: admin
      password: admin